### ISSUE TITLE
似乎还缺少一些fanuc功能包呀

### ISSUE THREAD

**Issue by hxqup** [leixiaoyuasdl/ur_grinding#1]
您好，我也是做ur机械臂打磨的，想参考一些你的代码
但当我运行ur_grinding.launch文件时，似乎缺少fanuc_r1000ia_support功能包，能不能麻烦你再出一个详细一点的教程呀
不好意思，实在有点笨

**Comment by leixiaoyuasdl** [comment]
应该可以了

**Comment by hxqup** [comment]
好像还是缺少一些依赖，比如post_processor的CMakeList就有fanuc_post_processor这个功能包依赖
然后如果我下载bezier这个库的话，他会提醒我缺少bezier_library，是不是需要把这个功能包改个名字呀

**Comment by leixiaoyuasdl** [comment]
是的，因为版本问题最新版本的bezier不能用，已经上传了所需版本的bezier库。需要注意的是VTK和PCL也有版本要求。

**Comment by hxqup** [comment]
我还想请问一下这个industrial_core是哪个包呀，这个包我也没在github上找到

**Comment by hxqup** [comment]
我还想请问一下ur_grinding那个package.xml文件里面写的industrial_core是哪个功能包呀，其他的我都在github上找到了，但是这个industrial_core我没有找到同名的包，哈哈哈不好意思

**Comment by hxqup** [comment]
还有scanning这个功能包似乎依赖的也是fanuc的一些依赖，包括fanuc的moveit依赖，我不知道这个是就是这个样子的还是我需要改一下

**Comment by leixiaoyuasdl** [comment]
一开始代码都用的fanuc的前缀后来懒得改就一直沿用了，不过关于fabnuc机器人的依赖都可以删掉，可能我没删完。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月30日(周五) 晚上11:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [leixiaoyuasdl/ur_grinding] 似乎还缺少一些fanuc功能包呀 (Issue #1)




 
还有scanning这个功能包似乎依赖的也是fanuc的一些依赖，包括fanuc的moveit依赖，我不知道这个是就是这个样子的还是我需要改一下

**Comment by leixiaoyuasdl** [comment]
你百度ros ＋ industrial



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月30日(周五) 晚上11:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [leixiaoyuasdl/ur_grinding] 似乎还缺少一些fanuc功能包呀 (Issue #1)




 
我还想请问一下ur_grinding那个package.xml文件里面写的industrial_core是哪个功能包呀
