### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by hxqup** [leixiaoyuasdl/ur_grinding#2]
[ 91%] Built target bezier_library
**make[2]: *** No rule to make target '/usr/lib/libvtkWrappingTools-6.3.a', needed by '/home/hxq/bezier_ws/devel/lib/fanuc_grinding_publish_meshfile/fanuc_grinding_publish_meshfile'.  Stop.**
**CMakeFiles/Makefile2:5416: recipe for target 'publish_meshfile/CMakeFiles/fanuc_grinding_publish_meshfile.dir/all' failed
make[1]: *** [publish_meshfile/CMakeFiles/fanuc_grinding_publish_meshfile.dir/all] Error 2**
**make[1]: *** Waiting for unfinished jobs....**
Consolidate compiler generated dependencies of target bezier_library_surfacing
Consolidate compiler generated dependencies of target bezier_library_painting
Consolidate compiler generated dependencies of target bezier_library_tire_machining
[ 91%] Building CXX object bezier-pcl_dep/CMakeFiles/bezier_library_surfacing.dir/src/surfacing.cpp.o
[ 91%] Building CXX object bezier-pcl_dep/CMakeFiles/bezier_library_tire_machining.dir/src/tire_machining.cpp.o
[ 92%] Building CXX object bezier-pcl_dep/CMakeFiles/bezier_library_painting.dir/src/painting.cpp.o
cc1plus: warning: /usr/local/lib/cmake/vtk-8.0/UseVTK.cmake: not a directory
cc1plus: warning: /usr/local/lib/cmake/vtk-8.0/UseVTK.cmake: not a directory
cc1plus: warning: /usr/local/lib/cmake/vtk-8.0/UseVTK.cmake: not a directory
[ 92%] Linking CXX executable /home/hxq/bezier_ws/devel/lib/fanuc_grinding_scanning/fanuc_grinding_scanning
[ 92%] Linking CXX shared library /home/hxq/bezier_ws/devel/lib/libbezier_library_painting.so
CMakeFiles/fanuc_grinding_scanning.dir/src/scanning.cpp.o: In function `moveRobotScan(fanuc_grinding_scanning::ScanningServiceRequest_<std::allocator<void> >&, fanuc_grinding_scanning::ScanningServiceResponse_<std::allocator<void> >&)':
/home/hxq/bezier_ws/src/scanning/src/scanning.cpp:189: undefined reference to `pcl::DavidSDKGrabber::DavidSDKGrabber()'
/home/hxq/bezier_ws/src/scanning/src/scanning.cpp:191: undefined reference to `pcl::DavidSDKGrabber::connect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned short)'
/home/hxq/bezier_ws/src/scanning/src/scanning.cpp:192: undefined reference to `pcl::DavidSDKGrabber::isConnected() const'
/home/hxq/bezier_ws/src/scanning/src/scanning.cpp:200: undefined reference to `pcl::DavidSDKGrabber::setLocalAndRemotePaths(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/home/hxq/bezier_ws/src/scanning/src/scanning.cpp:201: undefined reference to `pcl::DavidSDKGrabber::setFileFormatToSTL()'
/home/hxq/bezier_ws/src/scanning/src/scanning.cpp:229: undefined reference to `pcl::DavidSDKGrabber::grabSingleCloud(pcl::PointCloud<pcl::PointXYZ>&)'
collect2: error: ld returned 1 exit status
scanning/CMakeFiles/fanuc_grinding_scanning.dir/build.make:475: recipe for target '/home/hxq/bezier_ws/devel/lib/fanuc_grinding_scanning/fanuc_grinding_scanning' failed
**make[2]: *** [/home/hxq/bezier_ws/devel/lib/fanuc_grinding_scanning/fanuc_grinding_scanning] Error 1
CMakeFiles/Makefile2:10639: recipe for target 'scanning/CMakeFiles/fanuc_grinding_scanning.dir/all' failed
make[1]: *** [scanning/CMakeFiles/fanuc_grinding_scanning.dir/all] Error 2**
[ 93%] Linking CXX shared library /home/hxq/bezier_ws/devel/lib/libbezier_library_surfacing.so
[ 93%] Built target bezier_library_painting
[ 94%] Linking CXX shared library /home/hxq/bezier_ws/devel/lib/libbezier_library_tire_machining.so
[ 94%] Built target bezier_library_surfacing
[ 94%] Built target bezier_library_tire_machining
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j12 -l12" failed

**Comment by hxqup** [comment]
你好，我最近编译的时候发现这两个错误，一直解决不了，想请问一下你之前有遇到这样的错误吗

**Comment by leixiaoyuasdl** [comment]
这个是因为你在安装pcl，cmake的时候要勾上DavidSDK相关选项。我重新上传了新版本，使代码不再需要DavidSDK，你可以重新编译一下。

**Comment by leixiaoyuasdl** [comment]
这个代码是很久以前写的，有些问题，我也不太清楚，你遇到给我说我尽量修改。

**Comment by hxqup** [comment]
好的好的，我还想请问一下这个是必须连实体ur机器人才能跑吗
可以在仿真环境下跑吗
