### ISSUE TITLE
运行launch文件

### ISSUE THREAD

**Issue by hxqup** [leixiaoyuasdl/ur_grinding#3]
![image](https://user-images.githubusercontent.com/110043974/194870439-47e3eafa-b745-4025-a9ec-4f359c6cd497.png)

你好，我在pcl中添加davidSDK似乎编译成功了，然后我又改了改ur_grinding.launch文件，现在跑出来是这个样子，好像还有点问题

**Comment by hxqup** [comment]
[ INFO] [1665405402.754794406]: waitForService: Service [/scanning_service] has not been advertised, waiting...
QObject::connect: No such signal QDoubleSpinBox::valueChanged(int)
QObject::connect:  (receiver name: 'PathPlanningWidget_')
[ INFO] [1665405402.761771564]: waitForService: Service [/path_planning_service] has not been advertised, waiting...
**[ WARN] [1665405404.756747063]: ScanningWidget_ RViz panel could not connect to ROS service:
	/scanning_service
[ WARN] [1665405404.777017450]: PathPlanningWidget_ RViz panel could not connect to ROS service:
	/path_planning_service**
[ INFO] [1665405405.757238296]: waitForService: Service [/scanning_service] has not been advertised, waiting...
[ INFO] [1665405405.777615475]: waitForService: Service [/path_planning_service] has not been advertised, waiting...
[ WARN] [1665405406.185899776]: Waiting for scaled_pos_joint_traj_controller/follow_joint_trajectory to come up
[ WARN] [1665405407.759855822]: ScanningWidget_ RViz panel could not connect to ROS service:
	/scanning_service
[ WARN] [1665405407.780506852]: PathPlanningWidget_ RViz panel could not connect to ROS service:
	/path_planning_service
[ INFO] [1665405408.760887129]: waitForService: Service [/scanning_service] has not been advertised, waiting...
[ INFO] [1665405408.781074618]: waitForService: Service [/path_planning_service] has not been advertised, waiting...
**[ WARN] [1665405410.763074040]: ScanningWidget_ RViz panel could not connect to ROS service:
	/scanning_service
[ WARN] [1665405410.783745934]: PathPlanningWidget_ RViz panel could not connect to ROS service:
	/path_planning_service**
[ INFO] [1665405411.763526036]: waitForService: Service [/scanning_service] has not been advertised, waiting...
[ INFO] [1665405411.784223977]: waitForService: Service [/path_planning_service] has not been advertised, waiting...
[ WARN] [1665405412.186356680]: Waiting for scaled_pos_joint_traj_controller/follow_joint_trajectory to come up
[ WARN] [1665405413.766306205]: ScanningWidget_ RViz panel could not connect to ROS service:
	/scanning_service
[ WARN] [1665405413.786616336]: PathPlanningWidget_ RViz panel could not connect to ROS service:
	/path_planning_service
[ INFO] [1665405414.766801911]: waitForService: Service [/scanning_service] has not been advertised, waiting...
[ INFO] [1665405414.787704620]: waitForService: Service [/path_planning_service] has not been advertised, waiting...
[ WARN] [1665405416.773134906]: ScanningWidget_ RViz panel could not connect to ROS service:
	/scanning_service
[ WARN] [1665405416.793598654]: PathPlanningWidget_ RViz panel could not connect to ROS service:
	/path_planning_service
[ INFO] [1665405417.773586057]: waitForService: Service [/scanning_service] has not been advertised, waiting...
[ INFO] [1665405417.794264396]: waitForService: Service [/path_planning_service] has not been advertised, waiting...
[ERROR] [1665405418.186596346]: Action client not connected: scaled_pos_joint_traj_controller/follow_joint_trajectory

**Comment by hxqup** [comment]
上面是终端输出的东西

**Comment by leixiaoyuasdl** [comment]
我提交了一个新版本，我在另外一台电脑（ubuntu 20.04）能够正常编译运行（现在能够使用最新版的bizier库）。仿真的话，在launch文件里面启动仿真机器人就行了。

**Comment by leixiaoyuasdl** [comment]
我写了一个启动仿真的launch文件，你可以使用这个或者自己改成想用的机器人。另外，你需要自己下载新版bezier库，因为不再提供老版的库了。

**Comment by hxqup** [comment]
![image](https://user-images.githubusercontent.com/110043974/194989522-c81e287f-06f6-445b-95a7-cd366d293f71.png)

你好，现在就是前面都很正常，不会报错，但当我在仿真环境下导入stl文件时，就会报错

**Comment by leixiaoyuasdl** [comment]
点云文件能加载吗

**Comment by hxqup** [comment]
不行，不知道为啥，它说那个文件不存在

**Comment by leixiaoyuasdl** [comment]
你尝试加载一下  src/ur_grinding/scanning/meshes 下的stl和ply文件

**Comment by hxqup** [comment]
点云可以加载

**Comment by hxqup** [comment]
![image](https://user-images.githubusercontent.com/110043974/194993820-ccf428a4-7bb0-41c3-bd68-6a753663b78e.png)

现在是这个样子

**Comment by hxqup** [comment]
我要是点import CAD file的话，还是会报错：

/home/hxq/grinding_ws/src/scanning/meshes/DAC_580813.stl
**[publish_meshfile-11] process has died [pid 4445, exit code -11, cmd /home/hxq/grinding_ws/devel/lib/fanuc_grinding_publish_meshfile/fanuc_grinding_publish_meshfile __name:=publish_meshfile __log:=/home/hxq/.ros/log/63f3b926-4918-11ed-8ddf-50ebf62e895b/publish_meshfile-11.log].
log file: /home/hxq/.ros/log/63f3b926-4918-11ed-8ddf-50ebf62e895b/publish_meshfile-11.log**

**Comment by leixiaoyuasdl** [comment]
加载那个aa.ply（其实是一个叶片的点云，随便取的名字） ，可以让机器人运动一下，看一下除了加载stl还有什么问题。

**Comment by hxqup** [comment]
![image](https://user-images.githubusercontent.com/110043974/194994906-f1c67eea-8be9-4349-866a-527450b8471b.png)

好像不行诶 点compute_trajectory还是会报错

**Comment by leixiaoyuasdl** [comment]
你要先生成轨迹，再执行运动

**Comment by hxqup** [comment]
我点的是compute_trajectory,执行运动应该是execute_trajectory?

**Comment by leixiaoyuasdl** [comment]
你这里是程序崩溃了，并没有生成轨迹

**Comment by leixiaoyuasdl** [comment]
你将  /src/ur_grinding/rviz_plugin/config/robot_state_visualize.rviz 里面  
ScanningWidget_cad_file: 和 ScanningWidget_scan_filename:   后面的删除，然后正常操作一遍，在rviz里面重新保存一下 config

**Comment by hxqup** [comment]
好的 我试试

**Comment by leixiaoyuasdl** [comment]
是代码里面有个问题，它在找ply文件之前会先寻找stl存不存在，现在已经改过来了

**Comment by hxqup** [comment]
好的好的 谢谢 
我试试

**Comment by hxqup** [comment]
好像还是不行诶哥

只要我一点import_cad或者点compute_trajectory，就会显示process died，然后rviz那里也会报错

**Comment by leixiaoyuasdl** [comment]
刚刚我测试，这个是bezier版本的问题。16.04 还是得用之前我发的哪个版本，20.04直接用新的是没问题的。
你可以用之前的bezier包或者在Ubuntu20.04 上跑。

**Comment by leixiaoyuasdl** [comment]
如果你已经删掉之前的包，我可以重新上传一次

**Comment by hxqup** [comment]
好像还是不行
会不会是因为我用的ubuntu18.04

**Comment by leixiaoyuasdl** [comment]
不清楚，我这边20和16都没问题，我明天在ubuntu上18试一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月11日(周二) 晚上10:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [leixiaoyuasdl/ur_grinding] 运行launch文件 (Issue #3)




 
好像还是不行
 会不会是因为我用的ubuntu18.04

**Comment by leixiaoyuasdl** [comment]
ubuntu18.04有点问题，但是我最近没有时间，你可以在16或者20上试一下。

**Comment by hxqup** [comment]
好的好的，谢谢啦
